replicaCount: 1

image:
  repository: maybetuandat/vdt_backend
  tag: "1.0"  
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30002
  portName: vdt-api-port

database:
  host: "vdt-db-postgres-chart"
  port: "5432"
  name: "student_management"
  user: "postgres"
  password: "123456"

env:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi


healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60 
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}